<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\myexample\Controller\MyExampleController;

/**
 * @file
 * Contains Drupal\myexample\myexample.module
 *
 * Replace bad with good words in articles' body field
 */
function myexample_node_presave(EntityInterface $node){

  if($node->bundle() == 'article'){
    $wordreplacer = new MyExampleController();
    $bannedwords = $wordreplacer->getWordReplacer();

    foreach($bannedwords as $word){
      //dpm("$word->badword -> $word->goodword");
      $node->body->value = preg_replace('/\b' . $word->badword . '\b/', $word->goodword, $node->body->value);
      //$node->body->value = preg_replace("$word->badword)", $word->goodword, $node->body->value);
    }
  }
}